version: '3.1'

services:
   db:
     image: mysql:5.7
     secrets:
      - source: "mysqlrootpaswd"
        target: "mysqlrootpaswd"
        uid: "0"
        gid: "0"
        mode: 0444
      - source: "mysqlpaswd"
        target: "mysqlpaswd"
        uid: "0"
        gid: "0"
        mode: 0444
     environment:
       MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/mysqlrootpaswd"
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: "/run/secrets/mysqlpaswd"
     volumes:
      - wpsecret2:/var/lib/mysql
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == manager]
       restart_policy:
         condition: any

   wordpress:
     image: azcrig001cr001-on.azurecr.io/wp-engie:latest
     ports:
       - "80:80"
     depends_on:
       - db
     secrets:
       - source: "mysqlpaswd"
         target: "wpdbpaswd"
         uid: "0"
         gid: "0"
         mode: 0444
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_DATABASE: wordpress
       WORDPRESS_DB_PASSWORD_FILE: "/run/secrets/wpdbpaswd"
     deploy:
       mode: replicated
       replicas: 1
       placement:
         constraints: [node.role == manager]
       restart_policy:
         condition: on-failure

volumes:
  wpsecret2:
    external: true


secrets:
  mysqlrootpaswd:
    external:
      name: "app_mysqlrootpaswd"

secrets:
  mysqlpaswd:
    external:
      name: "app_mysqlpaswd"


