version: '3'

services:
   mysql:
     image: mariadb
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
      - wordpressvol:/var/lib/mysql
     deploy:
       mode: replicated
       replicas: 1
       resources:
         limits:
           memory: 1G
       placement:
         constraints:
         - node.role == worker
       restart_policy:
         condition: any
     networks:
       - wordpressnet

   wordpress:
     image: eitpocregistry-on.azurecr.io/eitpocregistry/wp-php71-memcached:1.0
     ports:
       - "80:80"
     networks:
       - wordpressnet
     depends_on:
       - mysql
     environment:
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_TABLE_PREFIX: wp_
        WORDPRESS_DB_HOST: mysql:3306 
     deploy:
       mode: replicated
       replicas: 1
       labels: [APP=WORDPRESS]
       # Service resource management
       resources:
         # Hard limit - Docker does not allow to allocate more
         limits:
           cpus: '0.25'
           memory: 1500M
         # Soft limit - Docker makes best effort to return to it
         reservations:
           cpus: '0.25'
           memory: 1000M  
       # service restart policy 
       restart_policy:
         condition: any
         delay: 5s
         max_attempts: 3
         window: 120s
       # placement constraint - in this case on 'worker' nodes only
       placement:
         constraints: [node.role == worker]


volumes:
  wordpressvol:
    #external: true


networks:
  wordpressnet:
    external: true
